# Generated by Django 5.1.4 on 2024-12-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buyertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyertoken',
            name='token',
        ),
        migrations.AddField(
            model_name='buyertoken',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyertoken',
            name='refesh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
