# Generated by Django 5.1.4 on 2024-12-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_buyertoken_token_buyertoken_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyertoken',
            old_name='refesh_token',
            new_name='refresh_token',
        ),
    ]
